#_______________________________________________________________________
#_______________________________________________________________________
#        _   __   _   _ _   _   _   _         _
#   |   |_| | _  | | | V | | | | / |_/ |_| | /
#   |__ | | |__| |_| |   | |_| | \ |   | | | \_
#    _  _         _ ___  _       _ ___   _                    / /
#   /  | | |\ |  \   |  | / | | /   |   \                    (^^)
#   \_ |_| | \| _/   |  | \ |_| \_  |  _/                    (____)o
#_______________________________________________________________________
#_______________________________________________________________________
#
#-----------------------------------------------------------------------
#   Copyright 2025, Rebecca Rashkin
#   -------------------------------
#   This code may be copied, redistributed, transformed, or built
#   upon in any format for educational, non-commercial purposes.
#
#   Please give me appropriate credit should you choose to use this
#   resource. Thank you :)
#-----------------------------------------------------------------------
#
#_______________________________________________________________________
#   //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\
#_______________________________________________________________________
#   DESCRIPTION
#   This file contains the configuration information for the quarto
#   project.
#_______________________________________________________________________

project:
  type        : website
  output-dir  : publish
  resources   :
    - assets/**
    - "CNAME"
    - darkmode.js

website:
  title: "Flying Rabbit Movement"
  favicon: assets/icons/rabbit-face.png
  open-graph:
    image: assets/photos-general-assets/flux-grass-line-art-black-square.png
    description: >
      Bodyweight Coach | Values clean code and
      documentation. Explore personal projects and a collection of
      resources on computer organization, development environment, and
      software tools.

  navbar:
    right:
      - text: "Locomotion"
        href: locomotion.qmd

      - text: "Handstands"
        href: handstands.qmd

      - text: "Services"
        href: services.qmd

      - text: "Contact"
        href: contact.qmd

    tools:
      - icon: moon
        href: "javascript:void(0)"

      - icon: instagram
        href: https://www.instagram.com/anonymous_rabbit/
      - icon: youtube
        href: https://www.youtube.com/@flying.rabbit.movement

  page-footer:
    center: "Â©2025 Rebecca Jennifer Rashkin"
    left  : flying.rabbit.movement (at) gmail (dot) com
    right :
      - icon: youtube
        href: https://www.youtube.com/@flying.rabbit.movement
      - icon: instagram
        href: https://www.instagram.com/anonymous_rabbit/
format:
  html:
    css               : flux-bunny-style.css
    code-fold         : true
    toc-title         : "Table of Contents"
    include-after-body: assets/ui-elements/footer.html
    highlight-style   : none

    # Always allow space for TOC so pages that have TOC don't shift
    toc: true
    toc-depth: 0